// DotnetSpa.Vue3Client/src/views/Dashboard.vue
<template>
  <div class="dashboard">
    <h2>Dashboard</h2>

    <Customers
      :customers="customers"
      :loading="loading"
      :selected-customer-id="selectedCustomer?.id"
      @select="onCustomerSelect"
      @update="onCustomerUpdate"
      @delete="onCustomerDelete"
    />

    <CustomerOrders
      v-if="hasSelectedCustomer"
      :customer="selectedCustomer"
      :orders="selectedCustomerOrders"
      :loading="loading"
      :has-orders="hasOrders"
    />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import Customers from '@/components/customers.vue'
import CustomerOrders from '@/components/customer-orders.vue'
import { useCustomerService } from '@/services/customer-service'
import type { Customer } from '@/models/customer'

const {
  customers,
  selectedCustomer,
  selectedCustomerOrders,
  loading,
  hasSelectedCustomer,
  hasOrders,
  selectCustomer,
  saveCustomerChanges,
  removeCustomer,
  refreshCustomers,
} = useCustomerService()

onMounted(() => {
  refreshCustomers()
})

const onCustomerSelect = (customer: Customer) => {
  selectCustomer(customer)
}

const onCustomerUpdate = (customer: Customer) => {
  saveCustomerChanges(customer)
}

const onCustomerDelete = (customerId: number) => {
  removeCustomer(customerId)
}

</script>

<style scoped lang="scss">
.dashboard {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  padding: 1rem;

  h2 {
    margin: 0;
  }
}
</style>

// DotnetSpa.ReactClient/app/routes/dashboard.tsx
import React, { useEffect } from 'react'
import Customers from '../components/customers'
import CustomerOrders from '../components/customer-orders'
import { useCustomerService } from '../services/customer-service'
import styles from './dashboard.module.scss'

const Dashboard: React.FC = () => {
  const {
    customers,
    selectedCustomer,
    selectedCustomerOrders,
    loading,
    hasSelectedCustomer,
    hasOrders,
    selectCustomer,
    refreshCustomers,
    saveCustomerChanges,
    removeCustomer,
  } = useCustomerService()

  useEffect(() => {
    refreshCustomers()
  }, [])

  const handleCustomerSelect = (customer: typeof selectedCustomer) => {
    if (customer) {
      selectCustomer(customer)
    }
  }

  const handleCustomerUpdate = (customer: typeof selectedCustomer) => {
    if (customer) {
      saveCustomerChanges(customer)
    }
  }

  const handleCustomerDelete = (customerId: number) => {
    removeCustomer(customerId)
  }

  return (
    <div className={styles.dashboard}>
      <h2>Dashboard</h2>

      <Customers
        customers={customers}
        loading={loading}
        selectedCustomerId={selectedCustomer?.id}
        onSelect={handleCustomerSelect}
        onUpdate={handleCustomerUpdate}
        onDelete={handleCustomerDelete}
      />

      {hasSelectedCustomer && (
        <CustomerOrders
          customer={selectedCustomer}
          orders={selectedCustomerOrders}
          loading={loading}
          hasOrders={hasOrders}
        />
      )}
    </div>
  )
}

export default Dashboard
