// DotnetSpa.ReactClient/app/components/customer-orders.tsx
import React from 'react'
import styles from './customer-orders.module.scss'
import type { Customer } from '../models/customer'
import type { Order } from '../models/order'

interface CustomerOrdersProps {
  customer?: Customer
  orders: Order[]
  loading: boolean
  hasOrders: boolean
}

const CustomerOrders: React.FC<CustomerOrdersProps> = ({
  customer,
  orders,
  loading,
  hasOrders,
}) => {
  const formatCurrency = (value: number) =>
    new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
    }).format(value)

  if (!customer) return null

  return (
    <div className={styles.customerOrders}>
      {loading ? (
        <p>Getting Orders for Customer...</p>
      ) : hasOrders ? (
        <table>
          <caption>
            {customer.firstName} {customer.lastName}&apos;s Orders
          </caption>
          <thead>
            <tr className={styles.tableHeader}>
              <td>Id</td>
              <td>Total Price</td>
            </tr>
          </thead>
          <tbody>
            {orders.map((order) => (
              <tr key={order.id}>
                <td>{order.id}</td>
                <td>{formatCurrency(order.totalPrice)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <p>No Orders found.</p>
      )}
    </div>
  )
}

export default CustomerOrders

// DotnetSpa.VueClient/src/components/CustomerOrders.vue
<template>
  <div class="customer-orders">
    <p v-if="loading">Getting Orders for Customer...</p>
    <table v-else-if="orders && orders.length > 0">
      <caption>{{customer.firstName}} {{customer.lastName}}'s Orders</caption>
      <tr class="table-header">
        <td>Id</td>
        <td>Total Price</td>
      </tr>
      <tr v-for="order in orders" v-bind:key="order.id">
        <td>{{order.id}}</td>
        <td>{{order.totalPrice}}</td>
      </tr>
    </table>
    <p v-else>No Orders found.</p>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import OrderModel from '@/models/order';
import CustomerModel from '@/models/customer';

@Component
export default class Orders extends Vue {
  loading: boolean = false;

  mounted(): void {
    if(!this.hasOrders) {
      this.refreshOrders();
    }
  }

  get customer(): CustomerModel {
    return this.$store.state.selectedCustomer;
  }

  get orders(): OrderModel[] {
    return this.$store.state.selectedCustomerOrders;
  }

  get hasOrders(): boolean {
    return !!this.orders && this.orders.length > 0;
  }

  refreshOrders(): void {
    this.loading = true;
      this.$store.dispatch('refreshCustomerOrders')
        .finally(() => this.loading = false);
  }
}
</script>

<style lang="scss" scoped>
  @import '../assets/styles/common';
</style>
