// DotnetSpa.Vue3Client/src/components/customer-orders.vue
<template>
  <div v-if="customer" class="customer-orders">
    <p v-if="loading">Getting Orders for Customer...</p>
    <table v-else-if="hasOrders">
      <caption>
        {{
          customer.firstName
        }}
        {{
          customer.lastName
        }}'s Orders
      </caption>
      <thead>
        <tr class="table-header">
          <td>Id</td>
          <td>Total Price</td>
        </tr>
      </thead>
      <tbody>
        <tr v-for="order in orders" :key="order.id">
          <td>{{ order.id }}</td>
          <td>{{ formatCurrency(order.totalPrice) }}</td>
        </tr>
      </tbody>
    </table>
    <p v-else>No Orders found.</p>
  </div>
</template>

<script setup lang="ts">
import { type Customer } from '@/models/customer'
import { type Order } from '@/models/order'

defineProps<{
  customer: Customer | undefined
  orders: Order[]
  loading: boolean
  hasOrders: boolean
}>()

const formatCurrency = (value: number) => {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
  }).format(value)
}

</script>

<style lang="scss" scoped>
@import '@/assets/styles/common';
</style>

// DotnetSpa.ReactClient/app/components/customer-orders.tsx
import React from 'react'
import styles from './customer-orders.module.scss'
import type { Customer } from '../models/customer'
import type { Order } from '../models/order'

interface CustomerOrdersProps {
  customer?: Customer
  orders: Order[]
  loading: boolean
  hasOrders: boolean
}

const CustomerOrders: React.FC<CustomerOrdersProps> = ({
  customer,
  orders,
  loading,
  hasOrders,
}) => {
  const formatCurrency = (value: number) =>
    new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 2,
    }).format(value)

  if (!customer) return null

  return (
    <div className={styles.customerOrders}>
      {loading ? (
        <p>Getting Orders for Customer...</p>
      ) : hasOrders ? (
        <table>
          <caption>
            {customer.firstName} {customer.lastName}&apos;s Orders
          </caption>
          <thead>
            <tr className={styles.tableHeader}>
              <td>Id</td>
              <td>Total Price</td>
            </tr>
          </thead>
          <tbody>
            {orders.map((order) => (
              <tr key={order.id}>
                <td>{order.id}</td>
                <td>{formatCurrency(order.totalPrice)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <p>No Orders found.</p>
      )}
    </div>
  )
}

export default CustomerOrders
